apiVersion: v1
kind: Service
metadata:
  name: play-loadbserv
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: play-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: play-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: play-pod
  template:
    metadata:
      labels:
        app: play-pod
    spec:
      containers:
      - name: contk8splayground
        image: localhost:32000/k8splayground
        ports:
        - containerPort: 8080