apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: play-service
            port: 
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: play-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: play-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: play-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: play-pod
  template:
    metadata:
      labels:
        app: play-pod
    spec:
      containers:
      - name: contk8splayground
        image: localhost:32000/k8splayground
        ports:
        - containerPort: 8080